name: 3D-Contrib

on:
  schedule: # runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-graph
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Generate 3D-Contrib
        run: |
          npm install -g @yiskylee/3d-contrib
          3d-contrib --username ${{ github.repository_owner }} --output profile-3d-contrib/profile-night-green.svg --theme night-green
          
      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/.
          git commit -m "3d-contrib update" || exit 0
          git push 