name: Update GitHub Stats

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # allows manual triggering

jobs:
  update-stats:
    name: Force refresh GitHub stats
    runs-on: ubuntu-latest
    steps:
      - name: Update Profile Views
        run: |
          # Force refresh of profile views counter
          curl -s "https://komarev.com/ghpvc/?username=kunalsanga&style=flat-square&color=blue&v=$(date +%s)" > /dev/null
          
      - name: Update Activity Graph
        run: |
          # Force refresh of activity graph
          curl -s "https://github-readme-activity-graph.vercel.app/graph?username=kunalsanga&theme=react-dark&v=$(date +%s)" > /dev/null
          
      - name: Update Profile Summary Cards
        run: |
          # Force refresh of profile summary cards
          curl -s "https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=kunalsanga&theme=radical&v=$(date +%s)" > /dev/null
          curl -s "https://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=kunalsanga&theme=radical&v=$(date +%s)" > /dev/null
          curl -s "https://github-profile-summary-cards.vercel.app/api/cards/most-commit-language?username=kunalsanga&theme=radical&v=$(date +%s)" > /dev/null
          curl -s "https://github-profile-summary-cards.vercel.app/api/cards/stats?username=kunalsanga&theme=radical&v=$(date +%s)" > /dev/null
          curl -s "https://github-profile-summary-cards.vercel.app/api/cards/productive-time?username=kunalsanga&theme=radical&v=$(date +%s)" > /dev/null
          
      - name: Update GitHub Stats
        run: |
          # Force refresh of GitHub stats
          curl -s "https://github-readme-stats.vercel.app/api?username=kunalsanga&show_icons=true&theme=radical&v=$(date +%s)" > /dev/null
          curl -s "https://github-readme-streak-stats.herokuapp.com/?user=kunalsanga&theme=radical&v=$(date +%s)" > /dev/null
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=kunalsanga&layout=compact&theme=radical&v=$(date +%s)" > /dev/null
          
      - name: Update 3D Contribution Graph
        run: |
          # Force refresh of 3D contribution graph
          curl -s "https://raw.githubusercontent.com/kunalsanga/kunalsanga/main/profile-3d-contrib/profile-night-rainbow.svg?v=$(date +%s)" > /dev/null 